### ISSUE TITLE
taking contributions? (Type:Invst support)

### ISSUE THREAD

**Issue by pacificbrian** [dmjones/qif#1]
Hi.   What is status of qif package?
I found this parser is fully functional, so perhaps update the README.....

I have a patch to add support for parsing of "!Type:Invst" transactions.
Are you interested to consider merging?

Should I post as pull request?

**Comment by dmjones** [comment]
Hello. I’m not actively using the package, but happy to take contributions.
And yes, the README needs an update.

I’m travelling for business so it may take at least a week to review and
merge a PR. But feel free to create one.

**Comment by pacificbrian** [comment]
Can't believe it took one whole year....  but I finally sent it!
See  dmjones/qif/pull/2
